resolver: nightly-2016-11-05
packages:

packages:
- heed-backend
- heed-frontend
- heed-lib

extra-deps:
- ghcjs-dom-0.5.0.2
- ref-tf-0.4.0.1
- react-flux-1.2.3
- ghcjs-dom-jsaddle-0.5.0.0
- jsaddle-dom-0.5.0.1
- jsaddle-0.5.2.0
