resolver: nightly-2016-11-24
packages:

packages:
- heed-backend
- heed-frontend
- heed-lib
- location: './opaleye-trans'
  extra-dep: true

extra-deps:
- ref-tf-0.4.0.1
- react-flux-1.2.3
- jsaddle-0.7.0.0
- jsaddle-dom-0.7.0.0
