resolver: nightly-2016-12-31

packages:
- heed-backend
- heed-lib
- heed-vty
- location: './opaleye-trans'
  extra-dep: true

extra-deps:
- brick-0.16
- text-zipper-0.9
- vty-5.14
- store-0.3
- vector-0.12.0.0
- websockets-0.10.0.0
- wuss-1.1.3
- scientific-0.3.4.10
- integer-logarithms-1
