resolver: nightly-2017-01-17

packages:
- heed-backend
- heed-lib
- heed-vty

extra-deps:
- brick-0.17
- hspec-2.4.0
- hspec-core-2.4.0
- hspec-discover-2.4.0
- hspec-smallcheck-0.4.2
- html-entities-1.1.2
- integer-logarithms-1
- opaleye-trans-0.3.4
- scientific-0.3.4.10
- store-0.3
- text-zipper-0.9
- uri-0.1.6.4
- vector-0.12.0.0
- vty-5.15
- websockets-0.10.0.0
- wuss-1.1.3
